model:
  id: Qwen/Qwen3-4B-Instruct-2507
peft:
  method: qlora
  r: 64
  alpha: 16
  dropout: 0.05
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj
train:
  lr: 2e-5
  epochs: 3
  batch_size: 4
  grad_accum: 16
  max_seq_len: 4096
  bf16: true
  gradient_ckpt: true
gen:
  max_new_tokens: 64
  temperature: 0.1
  top_p: 0.9
